---
title: "mrktc_origdest_catchment"
output: html_document
date: "2024-02-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)

```

```{r libraries, include = F}
library(readr)
library(tidyverse)
library(sf)
library(ggplot2)
library(here)
library(knitr)
library(ggpubr)
library(RColorBrewer)
library(rmarkdown)
library(igraph)
library(ggraph)
```

```{r theme, include = F}
custom_theme <- theme_bw() + 
  theme(text = element_text(family = "serif", size = 10))
theme_set(custom_theme)

tanzania_pal <- rep(brewer.pal(9,"Pastel1"),times=4)
market_pal <- c(brewer.pal(8, "Dark2"), "#FFA500", "#6A3D9A", "#33A02C")
```

## Quick Network Analysis ##


```{r load-data, include = F}

# Market survey A data:
mrkta_gps <- read_csv(here("data/data-cleaning_data/mrkta_gps_tanzania_final.csv")) 

# Market Survey C data
mrktc_gps <- read_csv(here("data/data-cleaning_data/mrktc_allgps_tanzania_final.csv"))

mrktc_coords <- mrktc_gps %>%
  mutate(lat = str_split(`gps.coordinates.of.the.market`, "\\s", simplify = TRUE)[, 1],
         long = str_split(`gps.coordinates.of.the.market`, "\\s", simplify = TRUE)[, 2])
mrktc_sf <- st_as_sf(mrktc_coords, coords = c("long","lat"),  crs = 4326)

# Market Survey C origins and destinations (from mrktc_origindest-cleaning_mar24)
mrktc_origdest <- read_csv(here("data/tanzania_data/mrktc_origdest_tanzania_finalv2.csv")) %>%
  select(-`...1`)

# Load Tanzania Shapefile:
sf_use_s2(FALSE)
twards_shp <- st_read(here("data/shapefiles/tzshp_final/twards_final.shp"))
tregs_shp <- st_read(here("data/shapefiles/tzshp_final/tregs_final.shp"))

```

# Script Producing Summary Origin/Destination data for MFA

# Data Overview:

Market Identifiers:
- fid
- date
- region
- district
- district20
- ward
- village
- market


## 2) Market Catchment Characteristics:

- total.area

- origin.maxdist
- origin.area
- origin.ndstrct
- origin.nwards


```{r origins}

# Subset only origin data (2021 rows with origin data)
mrktc_origins <- mrktc_origdest %>%
  select(
    fid,
    `2.sell.place.ward.final`,
    `2.sell.place.district.final`,
    `2.sell.place.region.final`
  ) %>%
  drop_na()

# create shapefile with point data for origins of animals at market:

mrktc_originspt_sf <- mrktc_origins %>%
  # join tanzania ward polygons to origins data:
  left_join(
    twards_shp %>% select(Region20_N, Dist20_N, Ward_N, geometry),
    by = c(`2.sell.place.ward.final` = "Ward_N", 
           `2.sell.place.district.final` = "Dist20_N",
           `2.sell.place.region.final` = "Region20_N")
  ) %>%
  st_as_sf() %>%
  # transform to point data (centroid/central point within ward)
  st_point_on_surface()

# this is the shapefile of ward polygons

mrktc_originspt_gps <- mrktc_originspt_sf %>%
  st_drop_geometry() %>%
  mutate(origlong = st_coordinates(mrktc_originspt_sf)[,1],
         origlat = st_coordinates(mrktc_originspt_sf)[,2])


```


```{r origmrktOD_data}

# Join origins data to markets data to create OD dataframe:

mrktorig_df <- mrktc_gps %>%
  # tidy market location data
  select(-district) %>%
  rename(
    mrkt.region = region,
    mrkt.district = district20,
    mrkt.ward = ward,
    mrkt.village = village,
    mrkt.name = market
  ) %>%
  # variables for market lat and long:
  mutate(mrktlong = str_split(`gps.coordinates.of.the.market`, "\\s", simplify = TRUE)[, 2],
         mrktlong = as.numeric(mrktlong),
         mrktlat = str_split(`gps.coordinates.of.the.market`, "\\s", simplify = TRUE)[, 1],
         mrktlat = as.numeric(mrktlat)
  ) %>%
  
  # Join origin gps data:
  left_join(mrktc_originspt_gps, by = "fid") %>%
  
  # exclude if no GPS data:
  filter(! (is.na(mrktlong)|is.na(mrktlat)|is.na(origlong)|is.na(origlat)))

```


```{r dstrctnetwork}
# Origin Destination data between distinct districts:

mrktorig_OD <- mrktorig_df %>%
    mutate(orig_distreg = paste(`2.sell.place.district.final`, `2.sell.place.region.final`, sep = "-"),
           mrkt_distreg = paste(`mrkt.district`,`mrkt.region`, sep = "-")) %>%
  select(fid,orig_distreg,mrkt_distreg) %>%
  group_by(orig_distreg,mrkt_distreg) %>%
  count() %>%
  # remove self-self loops:
  filter(!orig_distreg == mrkt_distreg)


###############
mrktorig_net <- graph_from_data_frame(d = mrktorig_OD)
# network <- graph_from_data_frame(d = mrktc_orignetwork, directed = TRUE)


plot(mrktorig_net)
plot(mrktorig_net, edge.width = E(mrktorig_net)$n)

ggraph(mrktorig_net, layout = "fr") +  # Using the Fruchterman-Reingold layout
  geom_edge_link(aes(width = n), color = "gray") + 
  geom_node_point(color = "blue", size = 5) +
  geom_node_text(aes(label = name), repel = TRUE, size = 3) +
  theme_graph() + 
  labs(title = "Network Visualization with ggraph")

```


```{r wardmvmtmap} 
# Assuming 'movements' has columns: origin_lon, origin_lat, destination_lon, destination_lat, and num_movements

# AA: We used R [35], a language and environment for statistical computing, as well as add-on
# packages (ggplot,flows,network) [36, 37] to perform data analysis and plotting

```
