---
title: "mrktc_origdest_catchment"
output: html_document
date: "2024-02-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)

```

```{r libraries, include = F}
library(readr)
library(tidyverse)
library(sf)
library(ggplot2)
library(here)
library(knitr)
library(ggpubr)
library(RColorBrewer)
library(rmarkdown)

```

```{r theme, include = F}
custom_theme <- theme_bw() + 
  theme(text = element_text(family = "serif", size = 10))
theme_set(custom_theme)

tanzania_pal <- rep(brewer.pal(9,"Pastel1"),times=4)
market_pal <- c(brewer.pal(8, "Dark2"), "#FFA500", "#6A3D9A", "#33A02C")
```

```{r load-data, include = F}

# Market survey A data:
mrkta_gps <- read_csv(here("data/data-cleaning_data/mrkta_gps_tanzania_final.csv")) 

# Market Survey C data
mrktc_gps <- read_csv(here("data/data-cleaning_data/mrktc_allgps_tanzania_final.csv"))

mrktc_coords <- mrktc_gps %>%
  mutate(lat = str_split(`gps.coordinates.of.the.market`, "\\s", simplify = TRUE)[, 1],
         long = str_split(`gps.coordinates.of.the.market`, "\\s", simplify = TRUE)[, 2])
mrktc_sf <- st_as_sf(mrktc_coords, coords = c("long","lat"),  crs = 4326)

# Market Survey C origins and destinations (from mrktc_origindest-cleaning_mar24)
mrktc_origdest <- read_csv(here("data/tanzania_data/mrktc_origdest_tanzania_final.csv")) %>%
  select(-`...1`)

# Load Tanzania Shapefile:
sf_use_s2(FALSE)
twards_shp <- st_read(here("data/shapefiles/tzshp_final/twards_final.shp"))
tregs_shp <- st_read(here("data/shapefiles/tzshp_final/tregs_final.shp"))

```

# Script Producing Summary Origin/Destination data for MFA

# Data Overview:

Market Identifiers:
- fid
- date
- region
- district
- district20
- ward
- village
- market


## 2) Market Catchment Characteristics:

- total.area

- origin.maxdist
- origin.area
- origin.ndstrct
- origin.nwards


```{r origins}

# Subset only origin data (2021 rows with origin data)
mrktc_origins <- mrktc_origdest %>%
  select(
    fid,
    `2.sell.place.ward.final`,
    `2.sell.place.district.final`,
    `2.sell.place.region.final`
  ) %>%
  drop_na()

mrktc_origins_sf <- mrktc_origins %>%
  left_join(
    twards_shp %>% select(Region20_N, Dist20_N, Ward_N, geometry),
    by = c(`2.sell.place.ward.final` = "Ward_N", 
           `2.sell.place.district.final` = "Dist20_N",
           `2.sell.place.region.final` = "Region20_N")
  )

mrktc_origins_sf <- st_as_sf(mrktc_origins_sf)
# this is the shapefile of ward polygons

mrktc_originspt_sf <- mrktc_origins_sf
mrktc_originspt_sf$geometry <- st_point_on_surface(mrktc_originspt_sf$geometry)
mrktc_originspt_gps <- mrktc_originspt_sf %>%
  st_drop_geometry() %>%
  mutate(origlong = st_coordinates(mrktc_originspt_sf)[,1],
         origlat = st_coordinates(mrktc_originspt_sf)[,2])

ggplot() +
  geom_sf(data = twards_shp)+
  geom_sf(data = mrktc_origins_sf, fill = "blue", alpha = 0.5)+
  geom_sf(data = mrktc_originspt_sf, col = "red", alpha = 0.5)+
  #geom_sf(data = st_point_on_surface(mrktc_origins_shp$geometry), col = "red", alpha = 0.5)+
  coord_sf()


ggplot() +
  geom_sf(data = tregs_shp, fill = NA)+
  geom_sf(data = tregs_shp %>% filter(Region_N %in% mrkta_gps$region), aes(fill = Region_N), alpha = 0.5)+
  geom_sf_text(data = tregs_shp %>% filter(Region_N %in% mrkta_gps$region), aes(label = Region_N), size = 2)+
  # geom_sf(data = twards_shp, fill = NA)+
  # geom_sf(data = twards_shp %>% filter(Region20_N %in% mrkta_gps$region), aes(fill = Region20_N), alpha = 0.5)+
  # geom_sf(data = mrktc_origins_sf, fill = "blue", alpha = 0.5)+
  geom_sf(data = mrktc_originspt_sf, col = "red", alpha = 0.5)+
  #geom_sf(data = st_point_on_surface(mrktc_origins_shp$geometry), col = "red", alpha = 0.5)+
  coord_sf()

```


```{r origcatchment}
library(geosphere)

mrktc_mrktorig <- mrktc_originspt_gps %>%
  # join market location:
  left_join(mrktc_gps %>% rename(
    mrkt.region = region,
    mrkt.district = district20,
    mrkt.ward = ward,
    mrkt.village = village,
    mrkt.name = market
  ) %>%
    select(-c(district)), 
  by = "fid") %>%
  # variables for market lat and long:
  mutate(mrktlong = str_split(`gps.coordinates.of.the.market`, "\\s", simplify = TRUE)[, 2],
         mrktlong = as.numeric(mrktlong),
         mrktlat = str_split(`gps.coordinates.of.the.market`, "\\s", simplify = TRUE)[, 1],
         mrktlat = as.numeric(mrktlat)
         ) %>%
  # distance between origin and market:
  mutate(origmrkt_dist = distHaversine(matrix(c(origlong, origlat), ncol = 2), 
                                  matrix(c(mrktlong, mrktlat), ncol = 2)),
         origmrkt_distkm = origmrkt_dist/1000
  )

mrktc_origsummary <- mrktc_mrktorig %>% 
  group_by(mrkt.region,mrkt.district,mrkt.ward,mrkt.village, mrkt.name) %>%
  summarise(
    origin.nmvmts = n(),
    origin.nregs = n_distinct(`2.sell.place.region.final`),
    origin.ndists = n_distinct(`2.sell.place.district.final`),
    origin.nwards = n_distinct(`2.sell.place.ward.final`),
    origin.maxdistkm = max(origmrkt_distkm),
    origin.meandistkm = mean(origmrkt_distkm),
    origin.meddistkm = median(origmrkt_distkm)
    ) 


# catchment area:

mrktc_mrktorig_geom <- mrktc_originspt_sf %>%
  # join market location:
  left_join(mrktc_gps %>% rename(
    mrkt.region = region,
    mrkt.district = district20,
    mrkt.ward = ward,
    mrkt.village = village,
    mrkt.name = market
  ) %>%
    select(-c(district)), 
  by = "fid") 

# Group by origin_id and create a convex hull for each group
catchment_areas <- mrktc_mrktorig_geom %>%
  group_by(mrkt.region,mrkt.district,mrkt.ward,mrkt.village, mrkt.name) %>%
  summarise(geometry = st_convex_hull(st_union(geometry))) %>%
  ungroup() %>%
  mutate(origin.areakm2 = st_area(.) / 10^6) # / 10^6 to convert m2 to km2

ggplot() +
  geom_sf(data = twards_shp, fill = NA) +
  geom_sf(data = catchment_areas, fill = 'blue', alpha = 0.3) +
  geom_sf(data = mrktc_originspt_sf, col = "red", alpha = 0.5)+
  geom_sf(data = mrktc_sf, color = 'black') +
  theme_minimal()


```

furthest distance travelled to market




- dest.maxdist
- dest.area
- dest.ndstrct
- dest.nwards

```{r destinations}

mrktc_dests <- mrktc_origdest %>%
  select(
    fid,
    `6.buy.place.ward.final`,
    `6.buy.place.district.final`,
    `6.buy.place.region.final`
  ) %>%
  drop_na()

mrktc_dests_sf <- mrktc_dests %>%
  left_join(
    twards_shp %>% select(Region20_N, Dist20_N, Ward_N, geometry),
    by = c(`6.buy.place.ward.final` = "Ward_N", 
           `6.buy.place.district.final` = "Dist20_N",
           `6.buy.place.region.final` = "Region20_N")
  )

mrktc_dests_sf <- st_as_sf(mrktc_dests_sf)

mrktc_destspt_sf <- mrktc_dests_sf
mrktc_destspt_sf$geometry <- st_point_on_surface(mrktc_destspt_sf$geometry)
mrktc_destspt_gps <- mrktc_destspt_sf %>%
  st_drop_geometry() %>%
  mutate(destlong = st_coordinates(mrktc_destspt_sf)[,1],
         destlat = st_coordinates(mrktc_destspt_sf)[,2])

ggplot() +
  geom_sf(data = twards_shp)+
  geom_sf(data = mrktc_dests_sf, fill = "blue", alpha = 0.5)+
  geom_sf(data = mrktc_destspt_sf, col = "red", alpha = 0.5)+
  #geom_sf(data = st_point_on_surface(mrktc_origins_shp$geometry), col = "red", alpha = 0.5)+
  coord_sf()

ggplot() +
  geom_sf(data = twards_shp, fill = NA)+
  geom_sf(data = twards_shp %>% filter(Region20_N %in% mrkta_gps$region), aes(fill = Region20_N), alpha = 0.5)+
  # geom_sf(data = mrktc_origins_sf, fill = "blue", alpha = 0.5)+
  geom_sf(data = mrktc_destspt_sf, col = "red", alpha = 0.5)+
  #geom_sf(data = st_point_on_surface(mrktc_origins_shp$geometry), col = "red", alpha = 0.5)+
  coord_sf()


```


```{r}

mrktc_mrktdest <- mrktc_destspt_gps %>%
  left_join(mrktc_gps %>% rename(
    mrkt.region = region,
    mrkt.district = district20,
    mrkt.ward = ward,
    mrkt.village = village,
    mrkt.name = market
  ) %>%
    select(-c(district)), 
  by = "fid") %>%
  # variables for market lat and long:
  mutate(mrktlong = str_split(`gps.coordinates.of.the.market`, "\\s", simplify = TRUE)[, 2],
         mrktlong = as.numeric(mrktlong),
         mrktlat = str_split(`gps.coordinates.of.the.market`, "\\s", simplify = TRUE)[, 1],
         mrktlat = as.numeric(mrktlat)
         ) %>%
  # distance between destination and market:
  mutate(destmrkt_dist = distHaversine(matrix(c(mrktlong, mrktlat), ncol = 2), 
                                  matrix(c(destlong, destlat), ncol = 2)),
         destmrkt_distkm = destmrkt_dist/1000
  )

mrktc_destsummary <- mrktc_mrktdest %>% 
  group_by(mrkt.region,mrkt.district,mrkt.ward,mrkt.village, mrkt.name) %>%
  summarise(
    dest.nmvmts = n(),
    dest.nregs = n_distinct(`6.buy.place.region.final`),
    dest.ndists = n_distinct(`6.buy.place.district.final`),
    dest.nwards = n_distinct(`6.buy.place.ward.final`),
    dest.maxdistkm = max(destmrkt_distkm),
    dest.meandistkm = mean(destmrkt_distkm),
    dest.meddistkm = median(destmrkt_distkm))

mrktc_mrktdest %>% 
  group_by(mrkt.region,mrkt.district,mrkt.ward,mrkt.village, mrkt.name,
           `6.buy.place.region.final`, `6.buy.place.district.final`, `6.buy.place.ward.final`) %>%
  count() %>% 
  # filter(mrkt.district !=`6.buy.place.district.final`) %>%
  # filter(mrkt.ward !=`6.buy.place.ward.final`) %>%
  View() 



# calc distance travelled to market:


# catchment area:

mrktc_mrktdest_geom <- mrktc_destspt_sf %>%
  # join market location:
  left_join(mrktc_gps %>% rename(
    mrkt.region = region,
    mrkt.district = district20,
    mrkt.ward = ward,
    mrkt.village = village,
    mrkt.name = market
  ) %>%
    select(-c(district)), 
  by = "fid") 

# Group by origin_id and create a convex hull for each group
destcatchment_areas <- mrktc_mrktdest_geom %>%
  group_by(mrkt.region,mrkt.district,mrkt.ward,mrkt.village, mrkt.name) %>%
  summarise(geometry = st_convex_hull(st_union(geometry))) %>%
  ungroup() %>%
  mutate(dest.areakm2 = st_area(.) / 10^6) # / 10^6 to convert m2 to km2

ggplot() +
  geom_sf(data = twards_shp, fill = NA) +
  geom_sf(data = destcatchment_areas, fill = 'blue', alpha = 0.3) +
  geom_sf(data = mrktc_destspt_sf, col = "red", alpha = 0.5)+
  geom_sf(data = mrktc_sf, color = 'black') +
  theme_minimal()


```



```{r joindata}

mrkt_origdest_join <- mrkta_gps %>% 
  # origins summary
  left_join(
    mrktc_origsummary, 
    by = c(region = "mrkt.region", district20 = "mrkt.district", ward = "mrkt.ward", village = "mrkt.village", market = "mrkt.name")
    ) %>%
  left_join(
    catchment_areas %>% st_drop_geometry(),
    by = c(region = "mrkt.region", district20 = "mrkt.district", ward = "mrkt.ward", village = "mrkt.village", market = "mrkt.name")
  ) %>%
  # destinations summary
  left_join(
    mrktc_destsummary, 
    by = c(region = "mrkt.region", district20 = "mrkt.district", ward = "mrkt.ward", village = "mrkt.village", market = "mrkt.name")
  ) %>% 
  left_join(
    destcatchment_areas %>% st_drop_geometry(),
    by = c(region = "mrkt.region", district20 = "mrkt.district", ward = "mrkt.ward", village = "mrkt.village", market = "mrkt.name")
  )

# write_csv(mrkt_origdest_join, file = here("data/tanzania_data/mrktdf_origdestforjoin_final.csv"))

```
