---
title: 'Tanzania Market Survey C: Descriptive Analysis'
author: "Beth Savagar"
date: "2024-01-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include = F}
library(readr)
library(tidyverse)
library(sf)
library(ggplot2)
library(here)
library(knitr)
library(ggpubr)
library(RColorBrewer)
library(rmarkdown)

```

```{r theme, include = F}
custom_theme <- theme_bw() + 
  theme(text = element_text(family = "serif", size = 10))
theme_set(custom_theme)

tanzania_pal <- rep(brewer.pal(9,"Pastel1"),times=4)
market_pal <- c(brewer.pal(8, "Dark2"), "#FFA500", "#6A3D9A", "#33A02C")
```

```{r load-data, include = F}
#tanzania map: 

# tdists_shp <- st_read(here("data/shapefiles/tza_admbnda_adm2_20181019.shp")) # with district boundaries
tregs_shp <- st_read(here("data/shapefiles/tza_admbnda_adm1_20181019.shp")) %>% # with region boundaries
   rename(
    "Country_N"=ADM0_EN,    
    "Country_NSw" = ADM0_SW,
    "Country_C"=ADM0_PCODE,
    "Region_Nam" = ADM1_EN,
    "Region_Cod" = ADM1_PCODE,
  )

twards_shp <- st_read(here("data/shapefiles/tza_admbnda_adm3_20181019.shp")) %>% # with ward boundaries
    rename(
    "Country_N"=ADM0_EN,    
    "Country_NSw" = ADM0_SW,
    "Country_C"=ADM0_PCODE,
    "Region_Nam" = ADM1_EN,
    "Region_Cod" = ADM1_PCODE,
    "District_N" = ADM2_EN,
    "District_C" = ADM2_PCODE,
    "Ward_Name"=ADM3_EN,
    "Ward_Code"= ADM3_PCODE
  )

tsettlements_shp <- st_read(here("data/shapefiles/GRID3_Tanzania_Settlement_Extents%2C_Version_01.01..shp")) # with ward boundaries
ttownsOth_shp <- st_read(here("data/shapefiles/tz_towns/tz-othertowns.shp")) # with ward boundaries
ttownsMaj_shp <- st_read(here("data/shapefiles/tz_towns/tz-majortowns.shp")) # with ward boundaries


mrkta_gps <- read_csv(here("data/tanzania_data/mrkta_gps_tanzania_final.csv")) %>%
  rename(region.final = region.geomatch.final, 
         district.final = district.geomatch.final,
         ward.final = ward.geomatch.final, 
         village.final = village.manual.final,
         market.final = market.manual.final)
mrktc_gps <- read_csv(here("data/tanzania_data/mrktc_allgps_tanzania_final.csv"))

# mrkta_generalinfo, need to link to cleaned update market location data
mrkta_info <-  read_csv(here("data/data-cleaning_data/mrkta_generalinfo_tanzania_final.csv")) %>%
  rename(region.final = region.geomatch.final, 
         district.final = district.geomatch.final,
         ward.final = ward.geomatch.final, 
         village.final = village.manual.final,
         market.final = market.manual.final)
mrktc_info <-  read_csv(here("data/data-cleaning_data/mrktc_generalinfo_tanzania_final.csv"))

```

```{r lookups, include = F, eval = T}
lkp_mrkttype <- read_csv(here("data/ecopprmarketscsvs/mrktc_lkpmrkt_type.csv"))
```

# Map of Survey C Locations
- Triangles indicate market survey C locations
- Circles indicate market survey A locations

```{r mrktGPS, include = F}

# Market A Map Data
mrkta_mapdata <- mrkta_gps %>%
  mutate(lat = str_split(`gps.coordinates.of.the.market`, "\\s", simplify = TRUE)[, 1],
         long = str_split(`gps.coordinates.of.the.market`, "\\s", simplify = TRUE)[, 2]) %>%
  filter(!is.na(lat), !is.na(long))

mrkta_sf <- st_as_sf(mrkta_mapdata, coords = c("long","lat"),  crs = 4326)

# Market C Map Data  
mrktc_mapdata <- mrktc_gps %>% 
  mutate(lat = str_split(`gps.coordinates.of.the.market`, "\\s", simplify = TRUE)[, 1],
         long = str_split(`gps.coordinates.of.the.market`, "\\s", simplify = TRUE)[, 2]) %>% 
  filter(!is.na(lat), !is.na(long))

mrktc_sf <- st_as_sf(mrktc_mapdata, coords = c("long","lat"),  crs = 4326)

```

### 1. Sales per Day

```{r mrktaSales, echo = F}
mrkttype_lkp1 <- mrkta_info %>%
  mutate(`3c.all.sales` = `3a.sheep.sales` + `3b.goat.sales`) %>%
  select(
    fid,
    date,
    country,
    region.final,
    district.final,
    ward.final,
    village.final,
    market.final,
    market.type.raw.A = market.type,
    all.sales = `3c.all.sales`,
    gps.coordinates.of.the.market,
    unique.row.identifier.uuid.
  )
  

```


### 2. Surveys per Market

```{r mrktc_nSurveys, echo = F}

nSurveys <- mrktc_info %>% 
  group_by(region.final, district.final, ward.final, village.final, market.final) %>% 
  summarise(number.surveys = n())

mrkttype_lkp2 <-  mrkttype_lkp1 %>%
  left_join(nSurveys, by = c("region.final","district.final","ward.final","village.final","market.final"))

mrkttype_lkp2 %>% select(all.sales, number.surveys) %>% summary()

```



<!-- ### 3. Urban-Rural Class of Market -->

<!-- ```{r urbanrural, echo = F} -->

<!-- sf_use_s2(FALSE) -->

<!-- settlementId <- sf::st_nearest_feature(mrkta_sf, tsettlements_shp) -->

<!-- mrkttype_lkp3 <- mrkttype_lkp2 %>% -->
<!--   mutate(settlementId = st_nearest_feature(mrkta_sf, tsettlements_shp)) %>% -->
<!--   left_join( -->
<!--     tsettlements_shp %>% st_drop_geometry() %>% select(settlementId = OBJECTID, urbanrural.class = type),  -->
<!--     by = c("settlementId") -->
<!--   ) %>%  -->
<!--   select(-settlementId) -->

<!-- ``` -->


<!-- ```{r mrkttypePlot, echo = F} -->

<!-- ggplot(mrkttype_lkp3 %>% filter(region.final != "mtwara"), aes(x=all.sales, y = number.surveys, col = urbanrural.class))+ -->
<!--   geom_point() -->

<!-- ``` -->

## Town Locations: 


```{r map}

Regions_Cmanual <- mrktc_sf %>% pull(region.final) %>% unique() %>% str_to_title()
Districts_Cmanual <- mrktc_sf %>% pull(district.final) %>% unique() %>% str_to_title()

ggplot() +
  geom_sf(data = tregs_shp, fill = "grey", alpha = 0.5, linewidth = 0.1) +
  geom_sf(data = ttownsMaj_shp, col = "red", size = 0.5, linewidth = 0.1)+
  geom_sf(data = ttownsOth_shp, col = "black", size = 0.5, linewidth = 0.1)+

  geom_sf(data = mrkta_sf, aes(col = region.final), alpha = 0.5, size = 1)+
  geom_sf_text(data = tregs_shp, aes(label = Region_Nam), size = 2)+
  # scale_fill_manual(values=rep(market_pal,2), guide = "none")+
  scale_colour_manual(values = rep(market_pal,2))+
  coord_sf()+
  labs(title = "Market locations and settlements",
       fill = "Tanzania region",
       col = "Market region")+
  theme(legend.position = "right", legend.box = "horizontal")

```


### Distance to nearest town:

```{r towndist, echo =F}

ttownsAll_shp <- bind_rows(ttownsMaj_shp %>% mutate(town.type = "major"), 
                       ttownsOth_shp %>% mutate(town.type = "other"))

townsId <- st_nearest_feature(mrkta_sf, ttownsAll_shp)

# townsId <- sf::st_nearest_feature(mrkta_sf, towns_all)
# 
# townsDf <- data.frame(
#   townsId = st_nearest_feature(mrkta_sf, ttownsAll_shp),
#   townsDist = st_distance(mrkta_sf, ttownsAll_shp[townsId, ], by_element = T) %>% as.numeric()
# ) %>%
#   mutate(townsDist_km = round(townsDist/1000, digits = 2)) %>%
#   left_join(ttownsAll_shp %>% st_drop_geometry() %>% mutate(townsId = 1:nrow(.)) %>% select(townsId, town.type), 
#             by = "townsId")
#    

mrkttype_lkp3 <- mrkttype_lkp2 %>%
  mutate(
    # identify closest town to market:
    townsId = st_nearest_feature(mrkta_sf, ttownsAll_shp),
    # calc distance to closest town:
    townsDist = st_distance(mrkta_sf, ttownsAll_shp[townsId, ], by_element = T) %>% as.numeric(),
    townsDist_km = round(townsDist/1000, digits = 2)) %>%
  # id towns as "major" or "other"
  left_join(ttownsAll_shp %>% st_drop_geometry() %>% mutate(townsId = 1:nrow(.)) %>% select(townsId, town.type), 
            by = "townsId") %>%
  select(-c("townsId", "townsDist"))



ggplot() +
  # plot tanzania:
  geom_sf(data = tregs_shp, fill = "grey", alpha = 0.5, linewidth = 0.1) +
  
  # plot location of nearest towns (col by major/other):
  geom_sf(data = ttownsAll_shp %>% slice(townsId), col = "black", size = 0.5, linewidth = 0.1)+
  geom_sf(data = mrkta_sf, aes(col = region.final), alpha = 0.5, size = 1)+
  geom_sf_text(data = tregs_shp, aes(label = Region_Nam), size = 2)+
  # scale_fill_manual(values=rep(market_pal,2), guide = "none")+
  scale_colour_manual(values = rep(market_pal,2))+
  coord_sf()+
  labs(title = "Market locations and settlements",
       fill = "Tanzania region",
       col = "Market region")+
  theme(legend.position = "right", legend.box = "horizontal")


```

