---
title: "tanzania_mapping-other-layers"
output: html_document
date: "2024-02-21"
---
---
title: "Tanzania Market Survey C: Data Cleaning"
author: "Beth Savagar"
date: "2023-02-07"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)

```

```{r libraries, include = F}
library(readr)
library(tidyverse)
library(sf)
library(ggplot2)
library(here)
library(knitr)
library(ggpubr)
library(RColorBrewer)
library(rmarkdown)
library(terra)

```

```{r load-tzboundaries, include = F}
# Load Tanzania Shapefile:
# tanzania_shp <- st_read(here("data/shapefiles/Districts and TC as 2020.shp")) # with district boundaries
# tregs_shp <- st_read(here("data/shapefiles/tzshp_final/tregs_final.shp")) 

# tdists_shp <- st_read(here("data/shapefiles/tzshp_final/tdists_final.shp")) # with district boundaries
twards_shp <- st_read(here("data/shapefiles/tzshp_final/twards_final.shp"))
twards_df <- twards_shp %>% 
  st_drop_geometry()

```


## 1. Population Density

### (i) Humanitarian data exchange - World Pop

```{r}

# Raster file:
pop_raster <- rast(here("data/shapefiles/tza_pd_2020_1km.tif"))
pop_df <- as.data.frame(pop_raster, xy = TRUE) %>%
  rename(humpop = "tza_pd_2020_1km")

summary(pop_df$humpop)
cuts <- quantile(pop_df$humpop, probs = c(0.10, 0.20, 0.3, 0.4, 0.5, 0.60, 0.7, 0.80, 0.9, 1))

pop_df <- pop_df %>% 
  # mutate(pop_cut = cut(humpop, breaks = 4)) %>%
  # mutate(pop_cut2 = cut(humpop, breaks = c(0, 0.85, 2.28,5,9.5,16.6,27.5, 43.5,70,125,65400))) 
  mutate(pop_cut2 = cut(humpop, breaks = c(0, cuts)))

ggplot() +
  geom_raster(data = pop_df, aes(x = x, y = y, fill = pop_cut2)) +
  # scale_fill_brewer(palette = "RdYlGn")+
  scale_fill_viridis_d()+
  # geom_raster(data = pop_df, aes(x = x, y = y, fill = humpop))+
  # scale_fill_gradient(high = "springgreen4", low= "grey90", name="Sum", 
  #         labels = cuts,
  #          breaks = cuts)
  coord_sf()
  
# ggplot() +
  # geom_raster(data = pop_df, aes(x = x, y = y, fill = humpop))+
  # scale_fill_gradient(high = "springgreen4", low= "grey90", name="Sum", 
  #         labels = cuts,
  #          breaks = cuts)+
  # coord_sf()

```


```{r tmap2}

# Use the 'extract' function with fun=sum to calculate total population per ward
twards_pop_shp <- twards_shp %>% 
  mutate(extract(pop_raster, twards_shp, fun=sum, na.rm=TRUE, ID = F)) %>%
  rename(humpop = "tza_pd_2020_1km") %>%
  mutate(extract(pop_raster, twards_shp, fun=mean, na.rm=TRUE, ID = F)) %>% 
  rename(meandensity = "tza_pd_2020_1km")


summary(twards_pop_shp$humpop)
wardcuts <- quantile(twards_pop_shp$humpop, probs = c(0.10, 0.20, 0.3, 0.4, 0.5, 0.60, 0.7, 0.80, 0.9, 1))

summary(twards_pop_shp$meandensity)
wardcuts2 <- quantile(twards_pop_shp$meandensity, probs = c(0.10, 0.20, 0.3, 0.4, 0.5, 0.60, 0.7, 0.80, 0.9, 1))

twards_pop_shp <- twards_pop_shp %>% 
  # mutate(pop_cut = cut(humpop, breaks = 4)) %>%
  # mutate(pop_cut2 = cut(humpop, breaks = c(0, 0.85, 2.28,5,9.5,16.6,27.5, 43.5,70,125,65400))) 
  mutate(wardcuts = cut(humpop, breaks = c(0, wardcuts))) %>%
  mutate(wardcuts2 = cut(meandensity, breaks = c(0, wardcuts2)))

ggplot() +
  # geom_raster(data = as.data.frame(pop_raster, xy = TRUE), aes(x = x, y = y, fill = tza_pd_2020_1km)) +
  geom_sf(data = twards_pop_shp, aes(fill = wardcuts))+
  # geom_sf(data = twards_pop_shp, aes(fill = wardcuts2))+
  scale_fill_viridis_d()+
  coord_sf()

ggplot() +
  # geom_raster(data = as.data.frame(pop_raster, xy = TRUE), aes(x = x, y = y, fill = tza_pd_2020_1km)) +
  geom_sf(data = twards_pop_shp, aes(fill = wardcuts2))+
  scale_fill_viridis_d()+
  coord_sf()


# pop_data_ascii <- read_csv(here("data/shapefiles/tza_pd_2020_1km_ASCII_XYZ.csv"))
# pop_data_sf <- st_as_sf(pop_data_ascii, coords = c("X", "Y"), crs = 4326)

# Spatially join points with wards
# sf_use_s2(FALSE)
# points_in_wards <- st_join(pop_data_sf, twards_shp)
# 
# ggplot() +
#   geom_sf(data = twards_shp, fill = NA, color = "black") + # Shapefile boundary
#   geom_sf(data = pop_data_sf, aes(size = Z), color = "red", alpha = 0.6) + # Population points
#   scale_size(range = c(1, 10), name = "Population Size") + # Adjust size scale as needed
#   theme_minimal() +
#   labs(title = "Population Distribution in Tanzania")

```


## 2. Animal Density

### (i) 

```{r sheep}

# Raster file:
shp_raster <- rast(here("data/shapefiles/glw_shp2015/5_Sh_2015_Da.tif"))
sheep_df <- as.data.frame(shp_raster, xy = TRUE) %>%
  rename("shppop" = `5_Sh_2015_Da`)


# Crop raster to the extent of the Tanzania shapefile
shp_raster_tanzania <- crop(shp_raster, ext(twards_shp))

shp_raster_tanzania_masked <- mask(shp_raster_tanzania, twards_shp)

sheep_df <- as.data.frame(shp_raster_tanzania_masked, xy = TRUE) %>%
  rename("shppop" = `5_Sh_2015_Da`)

ggplot() +
  geom_raster(data = sheep_df, aes(x = x, y = y, fill = shppop)) +
  # scale_fill_brewer(palette = "BrBG")+
  coord_sf()




# Use the 'extract' function with fun=sum to calculate total population per ward
twards_sheep_shp <- twards_shp %>% 
  mutate(extract(shp_raster, twards_shp, fun=sum, na.rm=TRUE, ID = F)) %>%
  rename(shppop = "5_Sh_2015_Da")


summary(twards_sheep_shp$shppop)
wardcuts <- quantile(twards_sheep_shp$shppop, probs = c(0.10, 0.20, 0.3, 0.4, 0.5, 0.60, 0.7, 0.80, 0.9, 1), na.rm = T)

twards_sheep_shp <- twards_sheep_shp %>% 
  # mutate(pop_cut = cut(humpop, breaks = 4)) %>%
  # mutate(pop_cut2 = cut(humpop, breaks = c(0, 0.85, 2.28,5,9.5,16.6,27.5, 43.5,70,125,65400))) 
  mutate(wardcuts = cut(shppop, breaks = c(0, wardcuts)))

ggplot() +
  # geom_raster(data = as.data.frame(pop_raster, xy = TRUE), aes(x = x, y = y, fill = tza_pd_2020_1km)) +
  geom_sf(data = twards_sheep_shp, aes(fill = wardcuts))+
  # geom_sf(data = twards_pop_shp, aes(fill = wardcuts2))+
  scale_fill_viridis_d()+
  coord_sf()


```

```{r goat}

# Raster file:
gt_raster <- rast(here("data/shapefiles/glw_goats2015/5_Gt_2015_Da.tif"))
goat_df <- as.data.frame(gt_raster, xy = TRUE) %>%
  rename("gtpop" = `5_Gt_2015_Da`)


# Crop raster to the extent of the Tanzania shapefile
gt_raster_tanzania <- crop(gt_raster, ext(twards_shp))

gt_raster_tanzania_masked <- mask(gt_raster_tanzania, twards_shp)

goat_df <- as.data.frame(gt_raster_tanzania_masked, xy = TRUE) %>%
  rename("gtpop" = `5_Gt_2015_Da`)

ggplot() +
  geom_raster(data = goat_df, aes(x = x, y = y, fill = gtpop)) +
  # scale_fill_brewer(palette = "BrBG")+
  coord_sf()


# Use the 'extract' function with fun=sum to calculate total population per ward
twards_goat_shp <- twards_shp %>% 
  mutate(extract(gt_raster, twards_shp, fun=sum, na.rm=TRUE, ID = F)) %>%
  rename(gtpop = "5_Gt_2015_Da")


summary(twards_goat_shp$gtpop)
wardcuts <- quantile(twards_goat_shp$gtpop, probs = c(0.10, 0.20, 0.3, 0.4, 0.5, 0.60, 0.7, 0.80, 0.9, 1), na.rm = T)

twards_goat_shp <- twards_goat_shp %>% 
  # mutate(pop_cut = cut(humpop, breaks = 4)) %>%
  # mutate(pop_cut2 = cut(humpop, breaks = c(0, 0.85, 2.28,5,9.5,16.6,27.5, 43.5,70,125,65400))) 
  mutate(wardcuts = cut(gtpop, breaks = c(0, wardcuts)))

ggplot() +
  # geom_raster(data = as.data.frame(pop_raster, xy = TRUE), aes(x = x, y = y, fill = tza_pd_2020_1km)) +
  geom_sf(data = twards_goat_shp, aes(fill = wardcuts))+
  # geom_sf(data = twards_pop_shp, aes(fill = wardcuts2))+
  scale_fill_viridis_d()+
  coord_sf()


```


```{r productionsystems}

# Raster file:
ps_raster <- rast(here("data/shapefiles/glw_ps2015/glw_ps2015_gis/glps_gleam_61113_10km.tif"))
ps_df <- as.data.frame(ps_raster, xy = TRUE) %>%
  rename("ps" = `CLASSNAME`)

ggplot() +
  geom_raster(data = ps_df, aes(x = x, y = y, fill = ps)) +
  coord_sf()


# Crop raster to the extent of the Tanzania shapefile
sheep_raster_tanzania <- crop(ps_raster, ext(twards_shp))

sheep_raster_tanzania_masked <- mask(sheep_raster_tanzania, twards_shp)

psT_df <- as.data.frame(sheep_raster_tanzania_masked, xy = TRUE) %>%
  rename("ps" = `CLASSNAME`)

ggplot() +
  geom_raster(data = psT_df, aes(x = x, y = y, fill = ps)) +
  scale_fill_brewer(palette = "Spectral")+
  coord_sf()



```
