---
title: "Tanzania Market Survey C: Data Cleaning"
author: "Beth Savagar"
date: "2023-02-07"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include = F}
library(readr)
library(tidyverse)
library(sf)
library(ggplot2)
library(here)
library(knitr)
library(ggpubr)
library(RColorBrewer)
library(readxl)

```

Use cleaned market survey C gps data to produce final "General Info" and "Market Activities" datasets

```{r dataload}

filesave <- F

mrktc_gps <- read_csv(here("data/tanzania_data/mrktc_allgps_tanzania_final.csv")) %>% select(-`...1`)

# mrkta_generalinfo, need to link to cleaned update market location data
mrktc_info_CLEAN <-  read_csv(here("data/tanzania_data/mrktc_generalinfo_tanzania_CLEAN.csv")) %>% select(-c("...1"))

mrktc_activities_raw <- read_csv(here("data/tanzania_data/mrktc_mrktactivities_tanzania.csv"))
```

<!-- ```{r actvtylkp} -->

<!-- lkp_mrktactvty <- read_csv(here("data/ecopprmarketscsvs/mrktc_lkpmrkt_actvty.csv")) %>% -->
<!--   mutate( -->
<!--     Code = as.character(Code), -->
<!--     `1.mrkt.activity.lkp` = case_match( -->
<!--       Code, -->
<!--       "-66" ~ "Other", -->
<!--       "1" ~ "Selling", -->
<!--       "2" ~ "Middleman", -->
<!--       "3" ~ "Trader", -->
<!--       "4" ~ "Buying" -->
<!--     ) -->
<!--   ) -->

<!-- lkp_sellplacetype <- read_csv(here("data/ecopprmarketscsvs/mrktc_lkpsell_placetype.csv")) %>% -->
<!--   mutate( -->
<!--     Code = as.character(Code), -->
<!--     `2.sell.placetype.lkp` = case_match( -->
<!--       Code, -->
<!--       "-66" ~ "Other", -->
<!--       "1" ~ "Village", -->
<!--       "2" ~ "Towncentre", -->
<!--       "3" ~ "Market", -->
<!--       "4" ~ "Abattoir" -->
<!--     ) -->
<!--   ) -->

<!-- lkp_selltransport <- read_csv(here("data/ecopprmarketscsvs/mrktc_lkpsell_trans.csv")) %>% -->
<!--   mutate( -->
<!--     Code = as.character(Code), -->
<!--     `4.sell.transport.lkp` = case_match( -->
<!--       Code, -->
<!--       "-77" ~ "Unknown", -->
<!--       "-66" ~ "Other", -->
<!--       "1" ~ "Foot", -->
<!--       "2" ~ "Vehicle", -->
<!--       "3" ~ "Cart" -->
<!--     ) -->
<!--   ) -->

<!-- lkp_buyplacetype <- lkp_sellplacetype -->

<!-- lkp_buytransport <- lkp_selltransport -->

<!-- lkp_sellreason <- read_csv(here("data/ecopprmarketscsvs/mrktc_lkpsell_reason.csv")) -->

<!-- lkp_buyreason <- read_csv(here("data/ecopprmarketscsvs/mrktc_lkpbuy_reason.csv")) -->

<!-- ``` -->

```{r infoClean}

# link mrktc Info to clean gps data and retain only variables of interest
mrktc_info <- left_join(
  mrktc_info_CLEAN %>% select(-c(contains(".code"), contains(".name"), contains("village"))),
  mrktc_gps %>% select(-c(country)),
  by = c("fid","date", "unique.row.identifier.uuid.")) %>% # can't join by "gps.coordinates.of.the.market" as some rows of original data have no location.
  select(
    fid,
    date,
    country,
    region,
    district,
    district20,
    ward,
    village,
    market,
    market.type, 
    respondent.role,
    other.market.visited,
    number.markets.visited,
    trader,
    trade.pattern,
    gps.coordinates.of.the.market = gps.coordinates.of.the.market.y,
    unique.row.identifier.uuid.
  ) %>%
  mutate(number.markets.visited = replace_na(number.markets.visited, 0)) %>% # For number.markets.visited replace NA with 0 
  mutate(trader = replace_na(trader, 0))

```

```{r resprole}

mrktc_info <- mrktc_info %>%
  mutate(
    "respondent.role" = tolower(`respondent.role`), # all lower case
    "respondent.role" = gsub("[[:punct:]]", " ", `respondent.role`), # remove punctuation
    "respondent.role" = trimws(`respondent.role`) #trim leading and trailing spaces
    )

# write.csv(mrktc_info %>% distinct(`respondent.role`), file = here("data/data-cleaning_data/respondentrole_mrktc.csv"))

```


```{r resprole2}
# order strings alphabetically
alphabetical <- function(words) {
  words <- sort(words)
  paste(words, collapse = " ")
}

# remove repeated words
repeats <- function(words) {
  paste(unique(words), collapse = " ")
}


resp.role <- read_excel(here("data/data-cleaning_data/respondentrole_mrktc.xlsx")) %>%
  select(`respondent.role`,`respondent.role.code` = "translation")


resp.role <- resp.role %>%
  mutate(respondent.role.code = tolower(`respondent.role.code`), # all lower case
         respondent.role.code = gsub("[[:punct:]]", " ", `respondent.role.code`), # remove punctuation
         # animals
         respondent.role.code = gsub("goat\\S*|sheep|livestock|bees|chickens|rabbits|animals", "", respondent.role.code),
         respondent.role.code = gsub("and|of|also|for", "", respondent.role.code),
         respondent.role.code = gsub("i have come to|in the market|i m|right here|various places|shop|meat|grilling|market", "", respondent.role.code),
         respondent.role.code = gsub("\\bbuy\\S*|purchase", "buyer", respondent.role.code),
         respondent.role.code = gsub("\\bsell\\S*", "seller", respondent.role.code),
         respondent.role.code = gsub("\\bbreed\\S*", "breeder", respondent.role.code),
         respondent.role.code = gsub("\\bbusiness\\S*", "businessman", respondent.role.code),
         respondent.role.code = gsub("\\bentrepreneur\\S*", "businessman", respondent.role.code),
         respondent.role.code = gsub("\\bslaughter\\S*", "slaughter", respondent.role.code),
         respondent.role.code = gsub("\\bsmuggle\\S*", "other", respondent.role.code),
         respondent.role.code = gsub("witch doctor", "other", respondent.role.code),
         respondent.role.code = gsub("soup seller", "other", respondent.role.code),
         respondent.role.code = gsub("\\brestaurant\\S*", "other", respondent.role.code),
         respondent.role.code = gsub("\\bmgalagajaa|\\bjalagaja|\\bunion|\\btrtt|\\bnyamikoma|\\bswindler|\\bstudent|\\bmufindi|\\bmfanty|\\bmf|\\bisunta|\\bisale|gulunga jilala", "other", respondent.role.code)) %>% 
  mutate(respondent.role.code = sapply(str_split(respondent.role.code, "\\s+"), alphabetical),
         respondent.role.code = sapply(str_split(respondent.role.code, "\\s+"), repeats),
         respondent.role.code = gsub("\\s+", " ", trimws(respondent.role.code)))

mrktc_info_final <- mrktc_info %>%
  left_join(resp.role,
            by = c("respondent.role")) %>%
  mutate(
    "respondent.buyer" = if_else(grepl("buyer", `respondent.role.code`), 1, 0),
    "respondent.seller" = if_else(grepl("seller", `respondent.role.code`), 1, 0),
    "respondent.business" = if_else(grepl("businessman", `respondent.role.code`), 1, 0),
    "respondent.middleman" = if_else(grepl("middleman|broker", `respondent.role.code`), 1, 0),
    "respondent.farmer" = if_else(grepl("farmer", `respondent.role.code`), 1, 0),
    "respondent.breeder" = if_else(grepl("breeder", `respondent.role.code`), 1, 0),
    "respondent.butcher" = if_else(grepl("butcher", `respondent.role.code`), 1, 0),
    "respondent.other" = if_else(grepl("vendor|food", `respondent.role.code`), 1, 0)) %>% 
  mutate("respondent.buyandsell" = if_else(respondent.buyer == 1 & respondent.seller == 1, 1, 0))
    
```

```{r saveinfo}

if(filesave){
  write_csv(mrktc_info_final, file = here("data/data-cleaning_data/mrktc_generalinfo_tanzania_final.csv"))
}


```