---
title: "mrkts_updatedistricts"
output: html_document
date: "2024-01-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include = F, echo = F, warning = F}
library(sf)
library(here)
library(tidyverse)
library(RColorBrewer)
library(lwgeom)
library(ggpubr)
```

```{r theme, include = F, echo = F, warning = F}
custom_theme <- theme_bw() + 
  theme(text = element_text(family = "Times New Roman", size = 10))
theme_set(custom_theme)

tanzania_pal <- rep(brewer.pal(9,"Pastel1"),times=4)
market_pal <- c(brewer.pal(8, "Dark2"), "#FFA500", "#6A3D9A", "#33A02C")
plotsave <- F
```

```{r dataload}
sf_use_s2(FALSE)

# Load final shapefiles:
tregs_final <- st_read(here("data/shapefiles/tzshp_final/tregs_final.shp")) # with region boundaries

tdists_final <- st_read(here("data/shapefiles/tzshp_final/tdists_final.shp")) # with dist boundaries

twards_final <- st_read(here("data/shapefiles/tzshp_final/twards_final.shp")) # with ward boundaries


## Update market A and market C gps location data

mrkta_gps <- read_csv(here("data/tanzania_data/mrkta_gps_tanzania_final.csv")) 

mrkta_info <-  read_csv(here("data/data-cleaning_data/mrkta_generalinfo_tanzania_final.csv")) 

mrktc_gps <- read_csv(here("data/tanzania_data/mrktc_allgps_tanzania_final.csv"))

mrktc_info <-  read_csv(here("data/data-cleaning_data/mrktc_generalinfo_tanzania_final.csv"))

mrktb_info <-  read_csv(here("data/data-cleaning_data/mrktb_generalinfo_tanzania_final.csv"))

```


```{r plotshps}


# Plot regions:
ggplot() +
  geom_sf(data = tregs_final, aes(fill = Region_N), alpha = 0.5) +
  scale_fill_manual(values = rep(tanzania_pal, 2), guide = "none") +
  labs(title = "Tanzania Regions")

# Plot districts (with region outline)
ggplot() +
  geom_sf(data = tdists_final, aes(fill = Region_N), alpha = 0.5) +
  geom_sf(data = tregs_final, col = "red", alpha = 0) +
  scale_fill_manual(values = rep(tanzania_pal, 2), guide = "none") +
  labs(title = "Tanzania Districts")
  
# Plot wards (with region outline)
ggplot() +
  geom_sf(data = twards_final, aes(fill = Dist20_N), alpha = 0.5) +
  geom_sf(data = tdists_final, col = "blue", linewidth = 0.5, alpha = 0) +
  geom_sf(data = tregs_final, col = "black", linewidth = 0.75, alpha = 0) +
  scale_fill_discrete(guide = "none") +
  # scale_fill_manual(values = rep(tanzania_pal, 10), guide = "none") +
  labs(title = "Tanzania Wards")

```
```{r mrkta_gps}

mrkta_mapdata <- mrkta_gps %>% 
  mutate(lat = str_split(`gps.coordinates.of.the.market`, "\\s", simplify = TRUE)[, 1],
         long = str_split(`gps.coordinates.of.the.market`, "\\s", simplify = TRUE)[, 2]) %>% 
  filter(!is.na(lat), !is.na(long))

mrkta_sf <- st_as_sf(mrkta_mapdata, coords = c("long","lat"),  crs = 4326)

mrkta_update <- mrkta_sf %>% 
  st_join(
    twards_final
  ) %>% 
  st_drop_geometry()

mrkta_update_gps <- mrkta_update %>%
  select(fid,
         date,
         country,
         region = region.geomatch.final,
         district = district.geomatch.final,
         district20 = Dist20_N,
         ward = ward.geomatch.final,
         village = village.manual.final,
         market = market.manual.final,
         gps.coordinates.of.the.market,
         unique.row.identifier.uuid.)

# Region and ward combinations are identical, it is only the district that has changed
mrkta_update %>% 
   filter(region.geomatch.final != tolower(Region20_N))

mrkta_update %>% 
  filter(district.geomatch.final != tolower(Dist20_N)) %>%
  select(starts_with("dist"), starts_with("Dist")) %>%
  distinct(district.geomatch.final,Dist20_N)

mrkta_update %>% 
   filter(ward.geomatch.final != tolower(Ward_N))


mrkta_info_update <- mrkta_info %>%
  left_join(mrkta_update_gps %>% select(fid, region, district, district20, ward,village,market),
            by = "fid") %>%
  select(fid,
         date,
         country,
         region, 
         district,
         district20,
         ward,
         village,
         market,
         market.type,
         name.of.respondent,
         `1.origins`,
         `2.destinations`,
         `3a.sheep.sales`,
         `3b.goat.sales`,
         `4.seasonal.variation.in.trade`,
         `4.if.yes.describe`,
         gps.coordinates.of.the.market,
         unique.row.identifier.uuid.)

# write.csv(mrkta_update_gps, here("data/tanzania_data/mrkta_gps_tanzania_final.csv"))
# write.csv(mrkta_info_update, here("data/tanzania_data/mrkta_generalinfo_tanzania_final.csv"))

```


```{r mrktc}

mrktc_update <- mrktc_gps %>%
  left_join(
    mrkta_update_gps %>% select(region, district, district20, ward, village, market), 
    by = c("region.final" = "region", "district.final" = "district", "ward.final" = "ward", "village.final" = "village", "market.final" = "market")
  )

mrktc_update_gps <- mrktc_update %>%
  select(fid,
         date,
         country,
         region = region.final,
         district = district.final,
         district20,
         ward = ward.final,
         village = village.final,
         market = market.final,
         gps.coordinates.of.the.market,
         unique.row.identifier.uuid.)

mrktc_info_update <- mrktc_info %>%
  left_join(mrktc_update_gps %>% select(fid, region, district, district20, ward,village,market),
            by = "fid") %>%
  select(fid,
         date,
         date.end,
         date.of.interview,
         date.final,
         country,
         region, 
         district,
         district20,
         ward,
         village,
         market,
         market.type,
         respondent.role,
         other.market.visited,
         number.markets.visited,
         trader,
         trade.pattern,
         gps.coordinates.of.the.market.final,
         unique.row.identifier.uuid.)
    
# write.csv(mrktc_update_gps, file = here("data/tanzania_data/mrktc_allgps_tanzania_final.csv"))
# write.csv(mrktc_info_update, file = here("data/tanzania_data/mrktc_generalinfo_tanzania_final.csv"))

```


```{r mrktb}

mrktb_info_update <- mrktb_info %>%
  left_join(mrkta_update_gps %>% select(region, district, district20, ward, village, market),
             by = c("region.final" = "region", "district.final" = "district", "ward.final" = "ward", "village.final" = "village", "market.final" = "market")) %>%
  select(fid,
         date,
         date.final,
         country,
         region = region.final,
         district = district.final,
         district20,
         ward = ward.final,
         village = village.final,
         market = market.final,
         market.type,
         sheep.0to12,
         sheep.adult,
         goat.0to12,
         goat.adult,
         gps.coordinates.of.the.market,
         unique.row.identifier.uuid.)
    
# write.csv(mrktb_info_update, file = here("data/tanzania_data/mrktb_generalinfo_tanzania_final.csv"))

```

