---
title: "Tanzania Market Survey C: Data Cleaning"
author: "Beth Savagar"
date: "2023-02-07"
output:
  pdf_document: default
  html_document: default
---

## review Other categories for data to tease out 
# - see excel sheets, recode and reform in mrktdf_definition dataframe

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include = F}
library(readr)
library(tidyverse)
library(sf)
library(ggplot2)
library(here)
library(knitr)
library(ggpubr)
library(RColorBrewer)
library(readxl)

```

Produce market C - Activities dataframe for use in MFA


## Load Data:

```{r dataload}

filesave <- F

# mrktc_gps <- read_csv(here("data/tanzania_data/mrktc_allgps_tanzania_final.csv"))
mrktc_gps <- read_csv(here("data/data-cleaning_data/mrktc_allgps_tanzania_final.csv"))

# mrkta_generalinfo, need to link to cleaned update market location data
mrktc_info <-  read_csv(here("data/data-cleaning_data/mrktc_generalinfo_tanzania_final.csv"))

mrktc_activities_clean <- read_csv(here("data/data-cleaning_data/mrktc_mrktactivities_tanzania_CLEAN.csv"))

# potentially read in origdest data at this stage too. 
```

```{r}

mrktc_all <- mrktc_info %>%
  left_join(mrktc_activities_clean %>% select(-unique.row.identifier.uuid.), 
            by = "fid")
colnames(mrktc_all)

# write.csv(mrktc_all, file = here("data/data-cleaning_data/mrktc_infoactvty_tanzania.csv"))

```


# Trader:

```{r trader}

mrktc_all %>% filter(trader ==1) %>% nrow()

# 1314 id as traders

mrktc_all %>% filter(trader == 1) %>% 
 
  group_by(respondent.role.code) %>% 
  count() %>% 
  View()


mrktc_all %>% 
  # of all traders
  filter(trader ==1) %>%
  mutate(`2.sell.thismrkt` = if_else(`4.sell.frommrkt` ==1, 1, 0),
         `6.buy.thismrkt` = if_else(`8.buy.atmarket`==1,1,0),
         `2.sell.market` = if_else(`2.sell.thismrkt`==1,0,`2.sell.market`),
         `6.buy.market` = if_else(`6.buy.thismrkt`==1,0,`6.buy.market`)) %>%
  # how many brought animals from a market (not this market)
  # and how many take animals to a market (not this market) 
  group_by(`2.sell.market`, `2.sell.thismrkt`,
           `6.buy.market`, `6.buy.thismrkt`) %>%
  count() %>% 
  View()



mrktc_all %>% 
  # of all traders
  filter(trader ==1) %>%
  mutate(`2.sell.thismrkt` = if_else(`4.sell.frommrkt` ==1, 1, 0),
         `6.buy.thismrkt` = if_else(`8.buy.atmarket`==1,1,0),
         `2.sell.market` = if_else(`2.sell.thismrkt`==1,0,`2.sell.market`),
         `6.buy.market` = if_else(`6.buy.thismrkt`==1,0,`6.buy.market`)) %>%
  # how many brought animals from a market (not this market)
  # and how many take animals to a market (not this market) 
  # filter(`2.sell.market` == 1 | `6.buy.market` == 1) %>%
  filter(`6.buy.market` == 1) %>%
  filter(`1.activity.trade`==1|`1.activity.buy`==1) %>% #,`1.activity.middleman`
  # count() %>% 
  View()

```